version: '3'
services:
  blue:
    image: kusitms29h/kusitms29h:latest
    container_name: blue
    expose:
      - 8080
    ports:
      - 8081:8080
    environment:
      - TZ=Asia/Seoul
  green:
    image: kusitms29h/kusitms29h:latest
    container_name: green
    expose:
      - 8080
    ports:
      - 8082:8080
    environment:
      - TZ=Asia/Seoul


