name: CI CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  check-skip:
    name: Check ot skip CI
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Main') || contains(github.event.head_commit.message, 'Global') }}
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: check-skip
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache
        uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create application-dev.yml
        run: |
          cd ./Backend
          cd ./src/main
          cd ./resources
          touch ./application.yml
          echo "$APPLICATION_DEV" > ./application.yml
        env:
          APPLICATION_MAIN: ${{ secrets.APPLICATION_DEV }}

      - name: Grant execute permission for gradlew
        run: |
          cd ./Backend
          chmod u+x gradlew

      - name: Build with Gradle
        run: |
          cd ./Backend
          ./gradlew build -x test

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_IMAGE: ${{secrets.DOCKER_IMAGE}}
        run: |
          cd ./Backend
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Send deploy.sh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.EC2_HOST}}
          username: ubuntu
          key: ${{secrets.EC2_PRIVATE_KEY}}
          source: "./scripts/"
          target: "/home/ubuntu/"
          port: 22

      - name: SCP Command to Transfer Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.EC2_HOST}}
          username: ubuntu
          key: ${{secrets.EC2_PRIVATE_KEY}}
          source: "./Backend/docker-compose.yml"
          target: "/home/ubuntu"
          port: 22

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.EC2_HOST}}
          username: ubuntu
          key: ${{secrets.EC2_PRIVATE_KEY}}
          port: 22
          script: |
            sudo docker pull ${{secrets.DOCKER_IMAGE}}
            sudo chmod 777 ./scripts/deploy.sh
            sudo cp ./scripts/deploy.sh ./deploy.sh
            sudo ./deploy.sh
            sudo docker image prune -f
